import { app_config } from "../config/app.config.mjs";
import { api } from "../config/bot.config.mjs";
import { ReviewModel } from "../models/review.model.mjs";
import { UserModel } from "../models/user.model.mjs";
import nodeCron from "node-cron";

export const get_admin = async () => {
    try {
        const admin = await UserModel.findOne({ is_admin: true });
        return admin;
    } catch (err) {
        return null;
    }
}

export const sendAdminNotification = async (ctx, users) => {
    try {
        const admin = await get_admin();
        if (!admin) return null;
        api.sendMessage(admin.id, `<b>✅ New user registered\n👤 Mention: ${user_mention(ctx.from)}\n🆔 UserID: <code>${ctx.from.id}</code>\n👑 Pos: <code>${users}</code></b>`, options);
        return true;
    } catch (err) {
        return null;
    }
}

export const assetCategories = [
    { id: "AI Agents", label: "AI Agents" },
    { id: "Marketing", label: "Marketing" },
    { id: "Finance", label: "Finance" },
    { id: "Crypto", label: "Crypto" },
    { id: "Mini Apps", label: "Mini Apps" },
    { id: "Utility", label: "Utility" },
    { id: "Dev Tools", label: "Dev Tools" },
    { id: "Education", label: "Education" },
    { id: "Govt Jobs", label: "Govt Jobs" },
    { id: "Career", label: "Career" },
    { id: "Global News", label: "Global News" },
    { id: "Business", label: "Business" },
    { id: "E-com", label: "E-com" },
    { id: "Gaming", label: "Gaming" },
    { id: "Lifestyle", label: "Lifestyle" },
    { id: "Health", label: "Health" },
    { id: "Travel", label: "Travel" },
    { id: "Entertainment", label: "Entertainment" },
    { id: "Technology", label: "Technology" },
    { id: "Other", label: "Other" }
];

export const options = {
    parse_mode: "HTML",
    protect_content: true,
    disable_web_page_preview: true
}

export const user_mention = (from) => {
    return from.username ? `@${from.username}` : `<a href="tg://user?id=${from.id}">${from.first_name}</a>`;
}

export const startMessage = () => {
    const text = `🤖 <b>Welcome to ${app_config.BOT.USERNAME}</b>\n\nThe Gold Standard for Telegram Intelligence.\n\n💭 Through this interface, you can discover high-performance applications or propose new listings to be added to our curated archive.\n\n<b>Network Status</b>\n• Real-time Metrics\n• Precision Discovery\n• Audited Security\n\n━━━━━━━━━━━━━━━━━━\n<b>Select an action to begin:</b>`;

    const keyboard = [
        [
            { text: "➕ Submit New Asset", callback_data: "/create_listing" },
        ],
        [
            { text: "👤 Profile", callback_data: "/my_profile" },
            { text: "🔍", switch_inline_query_current_chat: "" },
            { text: "🏆 Ranking", callback_data: "/view_ranks" }
        ],
        [
            { text: "📩 Verify Ownership", callback_data: "/verify_ownership" }
        ]
    ];

    return {
        text,
        keyboard
    };
}

export const getBotInfo = async (asset, go_to=null) => {
    const total_reviews = await ReviewModel.countDocuments({ asset_id: asset.asset_id });
    const text = `⚠️ <b>SAFETY WARNING</b>\n<i> The reviews and ratings provided here are generated by community members.Our system verifies the user ID, but we do not personally audit the internal code of listed bots or the content of channels.</i>\n──────────────\n⚖️ <b>LEGAL DISCLAIMER</b>\n<i> This platform acts as an intermediary for feedback only.We are not liable for any financial transactions, data loss, or disputes occurring outside this bot.Users are advised to exercise caution and perform their own due diligence before engaging with any listed asset.</i>\n──────────────\n\n<b>🏷 Title:</b> <b>${asset.title} (${asset.asset_type.toUpperCase()})</b>\n<b>📂 Category:</b> ${asset.category}\n<b>📊 Rating: ${asset.rating.toFixed(1)}/5.0</b>\n<b>🤖 Bot:</b> <b>@${asset.username.replace('@', '')}</b>`
    const keyboard = [
        [
            { text: "🔗 Open Link", url: `https://t.me/${asset.username}` }
        ],[
            { text: "📋 Add Review", callback_data: `/add_review ${asset.asset_id}` },
            { text: `🔎 View Reviews (${total_reviews})`, callback_data: `/view_reviews ${asset.asset_id} 0` }
        ], [
            { text: go_to ? "🔙 Back" : "🔙 Main Menu", callback_data: go_to ? go_to : "/start" }
        ]
    ]
    return { text, keyboard }
}

export const sendBroadcast = async (id, message_id_to_edit, message_id, callback) => {
    const admin = await get_admin();
    if (!admin || admin.id !== id) {
        return callback("❌ Access Denied: Admin Privileges Required");
    }
    await api.editMessageText(id, message_id_to_edit, `<b>✅ Broadcast in Progress</b>\n\nPlease wait while the broadcast is in progress.\n\n<b>Message ID:</b> <code>${message_id}</code>`, options);
    const obj = {
        message_id,
        sent: 0,
        success: 0,
        failed: 0
    }
    const bTask = nodeCron.schedule("*/3 * * * * *", async () => {
        const user = await UserModel.findOne({ broadcasted: { $ne: true } });
        if (!user) {
            bTask.stop();
            return callback(`<b>✅ Message Sent\n\nMessage has been sent successfully.\n\nMessage ID: <code>${obj.message_id}</code>\n\nSent: <code>${obj.sent}</code>\nSuccess: <code>${obj.success}</code>\nFailed: <code>${obj.failed}</code></b>`);
        }
        try {
            await api.copyMessage(user.id, id, obj.message_id);
            obj.success++;
        } catch (err) {
            obj.failed++;
        } finally {
            user.broadcasted = true;
            obj.sent++
        }
        await user.save();
    });
}